### ISSUE TITLE
about share more pretrained ckpt

### ISSUE THREAD

**Issue by yzf-code** [LirongWu/MAPE-PPI#10]
Thanks for your great work!
I noticed you provide a pre-trained model in ./trained_model/ for PPI prediction on STRING. However, according to your configs, the model structures under different settings of different datasets are not same. Can you share the ckpts of more datasets? For example, the ckpts of SHS27k and SHS148k under bfs and dfs? 
Thank you very much!

**Comment by LirongWu** [comment]
We are sorry to only provide pre-trained models for STRING because the SHS27k and SHS148k datasets are several orders of magnitude smaller than STRING, and we think that it is not slow to train them from scratch with a suitable combination of hyperparameters.

**Comment by yzf-code** [comment]
yeah, I noticed that, thanks for the reply.
