### ISSUE TITLE
python ./raw_data/data_process.py

### ISSUE THREAD

**Issue by kskim-phd** [LirongWu/MAPE-PPI#2]
Dear Authors,

I sincerely thank you for sharing your great work! (Congrat Spotlight too!)

Could you please share the following code? as it is not included in the current repo:

python ./raw_data/data_process.py

Thank you very much!

**Comment by LirongWu** [comment]
You can download the data and code from [Google Drive](https://drive.google.com/file/d/1hJVrQXddB9JK68z7jlIcLfd9AmTWwgJr/view?usp=sharing), from which you can find the processing code.

**Comment by kskim-phd** [comment]
> You can download the data and code from [Google Drive](https://drive.google.com/file/d/1hJVrQXddB9JK68z7jlIcLfd9AmTWwgJr/view?usp=sharing), from which you can find the processing code.

My mistake. Thank you!
