### ISSUE TITLE
How draw Fig 5?

### ISSUE THREAD

**Issue by DuanhaoranCC** [LirongWu/MAPE-PPI#6]
Dear Lirong:
Thank your representative work, I appreciate the analysis of Figure 5 and have some questions regarding its details.

1. For Figure 5(a), the center of the clustering is the codebook. What do the remaining 2D points represent? Are they node representations?

2. How was the distribution of amino acids counted? Specifically, how were the bar graphs obtained?

3. How is the distribution of amino acids calculated by the codebook in Figure 5(c)? As far as I understand, the codebook doesn't have a direct link to amino acids.

**Comment by LirongWu** [comment]
Thank you for your interest in this work.

1. For Figure 5(a), 2D points represent residue (node) representations, as the microenvironment describes the sequence and structural context at the residue level.

2. Figure 5(b), For each microenvironment, there will be plenty of different types of amino acids mapped to it. We count all of its corresponding residue types on the entire dataset, and we can get a distribution histogram corresponding to the microenvironments in Figure 5(b).

3. See Figure 5(b), each microenvironment encodes a "major residue" (with the highest bar), and we count the distribution of "major residue" types across all microenvironments to obtain Figure 5(c).

We sincerely hope that the above explanation will help you better understand Figure 5!
