### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by zwzhen-hnu** [LirongWu/MAPE-PPI#8]
Helllo Author,
./raw_data/data_process.py  file not found.
How can I get this file?
Thank you~

**Comment by LirongWu** [comment]
You can download it from [Google Drive](https://drive.google.com/file/d/1hJVrQXddB9JK68z7jlIcLfd9AmTWwgJr/view?usp=sharing), unzip it, and then you can find the data_process.py file in there.
